
group1 = (input("Enter Group 1 Name: "), int(input("Size of Group: ")), input("Date of Competition: "), input("Venue: "), input("Type of Medal: "))
group2 = (input("Enter Group 2 Name: "), int(input("Size of Group: ")), input("Date of Competition: "), input("Venue: "), input("Type of Medal: "))
group3 = (input("Enter Group 3 Name: "), int(input("Size of Group: ")), input("Date of Competition: "), input("Venue: "), input("Type of Medal: "))
group4 = (input("Enter Group 4 Name: "), int(input("Size of Group: ")), input("Date of Competition: "), input("Venue: "), input("Type of Medal: "))
group5 = (input("Enter Group 5 Name: "), int(input("Size of Group: ")), input("Date of Competition: "), input("Venue: "), input("Type of Medal: "))

print("\n--- Group 1 Info ---")
print("Group Name:", group1[0])
print("Size of Group:", group1[1])
print("Date of Competition:", group1[2])
print("Venue:", group1[3])
print("Type of Medal:", group1[4])

print("\n--- Group 2 Info ---")
print("Group Name:", group2[0])
print("Size of Group:", group2[1])
print("Date of Competition:", group2[2])
print("Venue:", group2[3])
print("Type of Medal:", group2[4])

print("\n--- Group 3 Info ---")
print("Group Name:", group3[0])
print("Size of Group:", group3[1])
print("Date of Competition:", group3[2])
print("Venue:", group3[3])
print("Type of Medal:", group3[4])

print("\n--- Group 4 Info ---")
print("Group Name:", group4[0])
print("Size of Group:", group4[1])
print("Date of Competition:", group4[2])
print("Venue:", group4[3])
print("Type of Medal:", group4[4])

print("\n--- Group 5 Info ---")
print("Group Name:", group5[0])
print("Size of Group:", group5[1])
print("Date of Competition:", group5[2])
print("Venue:", group5[3])
print("Type of Medal:", group5[4])
